localrules: done
report: "report/workflow.rst"


# -------- Config files -------- #
configfile: "config/config.yaml"
configfile: "config/cluster.yaml"


# -------- Container -------- #
# Fix underlying OS via Singularity
#container: "docker://lettucerap/anomaly:latest" # other than default, an image can be built from dockerfile in the repo so there's no need to pull from the hub


# -------- Load Rules -------- #
include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/trim.smk"
include: "rules/mapping.smk"
include: "rules/counting.smk"
include: "rules/drop.smk"

# -------- Target Rules -------- #
rule done:
    input:
        out + "/multiqc_report.html",
        drop_proj + "/config.yaml",
        #drop_proj + "/output/html/AberrantSplicing/blood--v34_summary.html",
    params:
        tmp=tmp,
    shell:
        """
        rm -rf ~/slurm/logs/*;
        find {params.tmp} -mindepth 1 -name tmp* -exec rm -r {{}} +;
        """