localrules: done
report: "report/workflow.rst"


# -------- Config files -------- #
configfile: "config/config.yaml"
configfile: "config/cluster.yaml"


# -------- Container -------- #
#container: "docker://lettucerap/anomaly:latest" # hosted image
singularity: "anomaly.sif" # using singularity instead

# -------- Load Rules -------- #
include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/trim.smk"
include: "rules/mapping.smk"
include: "rules/counting.smk"
include: "rules/drop.smk"

# -------- Target Rules -------- #
rule done:
    input:
        out + "/multiqc_report.html",
        drop_proj + "/output/html/AberrantSplicing/blood--v34_summary.html",
        drop_proj + "/output/html/AberrantExpression/Outrider/v34/Summary_blood.html"
    params:
        tmp=tmp,
    shell:
        """
        rm -rf ~/slurm/logs/*;
        find {params.tmp} -mindepth 1 -name tmp* -exec rm -r {{}} +;
        """