# mamba create --name rna-seq --file environment.yaml

name: anomaly
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc ==0.11.9
  - multiqc ==1.10
  - trim-galore ==0.6.6
  - star ==2.7.6a
  - samtools ==1.10
  - gatk4 ==4.2.0.0
  - rsem ==1.3.3
  - pandas ==1.2.3
  - pyyaml ==5.4.1
