cores:
  default: 1
  trimming: 5
  genome_index: 9
  mapping: 18
  counting: 12
mem:
  trimming: 36G
  genome_index: 45G
  mapping: 90G
  counting: 60G
time_min:
  default: 60
  trimming: 200
  genome_index: 180
  mapping: 420
  counting: 300
